Script should now be able to handle dayli AND timstep data

diff --git a/process_rain/create_dom_avg_pdf b/process_rain/create_dom_avg_pdf
--- a/process_rain/create_dom_avg_pdf
+++ b/process_rain/create_dom_avg_pdf
@@ -67,72 +67,78 @@ chmod -R 777 ${opt1_dir}
 
 
 for date in ${dates[*]};do
-    echo "Finding files for ${date}"
+  echo "$(basename $0): Finding files for ${date}"
 	for file in $(ls ${old_dir%/}/*${date}_*.${end} 2> /dev/null); do
 	      infile=${file##*/}
-
+        
         outfile=$(echo $infile|sed "s/${end}/nc/g")
         if [ ! -f ${ipt_dir%/}/${outfile} ];then
             if [ ${format} == 'ascii' ];then
-              echo "$0 : Creating $(basename $outfile)"
+              echo "$(basename $0) : Creating $(basename $outfile)"
                 ${workdir%/}/cappi_read_radar_rain -I ${old_dir%/}/${infile} -O ${ipt_dir%/}/${outfile}
                 if [ $? -ne 0 ];then
-                  echo "$0 : cappi_read_radar_rain failed"
+                  echo "$(basename $0) : cappi_read_radar_rain failed"
                   exit 257
                 fi
             else
-            		echo "$0 : call create_netcdf.py"
+              echo "$(basename $0) : call create_netcdf.py"
                 python2.7 ${workdir%/}/create_netcdf.py ${old_dir%/}/${infile} ${ipt_dir%/}/${outfile}
                 if [ $? -ne 0 ];then
-                  echo "$0 : create_netcdf failed"
+                  echo "$(basename $0) : create_netcdf failed"
                   exit 257
                 fi
-
+                if [ ! -f ${ipt_dir%}/${outfile} ];then
+                  #the create_netcdf script has finished but not the output 
+                  #file created, this means we probaply have created the netcdf
+                  #file from daily data, create an empty dummy string 
+                  touch ${ipt_dir%/}/${outfile}
+                  chmod 777 ${ipt_dir%/}/${outfile}
+               fi
             fi
-          file=${ipt_dir%/}/${outfile}
-	        pdffile=${opt1_dir%/}/${outfile%.nc}${pdf_suffix}.nc
-	        # only do anything if there is no zip file existing. Existence of zip file
-	        # implies everythng is done.
-	        if [ ! -f ${pdffile} ] ; then
-		        echo "$0 : Creating percentiles for $file"
-                  ${workdir%/}/radar_error -i ${file} -e ${workdir%/}/errfile.txt -o ${pdffile}
-                  #python2.7 ${workdir%/}/correct_rain.py ${pdffile} 'full'
+            for outfile in $(ls ${ipt_dir%/}/*${date}_????.nc 2> /dev/null); do
+              outfile=$(basename $outfile)
+              file=${ipt_dir%/}/${outfile}
+              pdffile=${opt1_dir%/}/${outfile%.nc}${pdf_suffix}.nc
+              # only do anything if there is no zip file existing. Existence of zip file
+              # implies everythng is done.
+              if [ ! -f ${pdffile} ] ; then
+                echo "$(basename $0) : Creating percentiles for $(basename $file)"
+                      ${workdir%/}/radar_error -i ${file} -e ${workdir%/}/errfile.txt -o ${pdffile}
+                      #python2.7 ${workdir%/}/correct_rain.py ${pdffile} 'full'
+                      if [ $? -ne 0 ];then
+                        echo "$(basename $0) : radar_error failed"
+                        exit 257
+                    fi
+
+              fi
+              # create domain averaged rainfall pdfs
+              avgfile=${file##*/}
+              avgfile=${opt2_dir%/}/${avgfile%.nc}${domavg_suffix}.nc
+              if [ ! -f ${avgfile} ];then
+                echo "$(basename $0) : Domain averaging $(basename ${avgfile})"
+                # do the domain average
+                python2.7 ${workdir%/}/make_domain_avg.py ${pdffile} ${avgfile} ${workdir%/}/mask.nc 0
+                    #python ${workdir%/}/correct_rain.py ${avgfile} 'time'
                   if [ $? -ne 0 ];then
-                    echo "$0 : radar_error failed"
-                    exit 257
-                fi
+                    echo "$(basename $0) : domain averaging failed"
+                        exit 257
+                    fi
 
-	        fi
-	        # create domain averaged rainfall pdfs
-	        avgfile=${file##*/}
-	        avgfile=${opt2_dir%/}/${avgfile%.nc}${domavg_suffix}.nc
-	        if [ ! -f ${avgfile} ];then
-                echo "Domain averaging ${avgfiles}"
-		        # do the domain average
-		        python2.7 ${workdir%/}/make_domain_avg.py ${pdffile} ${avgfile} ${workdir%/}/mask.nc 0
-                #python ${workdir%/}/correct_rain.py ${avgfile} 'time'
-              if [ $? -ne 0 ];then
-                    echo "$0 : radar_error failed"
-                    exit 257
                 fi
-
-            fi
-        fi
+              done
+          fi
 	  done
-    if [ "$(find ${ipt_dir%/}/*${date}_*.nc 2> /dev/null)" ];then
-         ${workdir%/}/create_time_avg ${workdir%/} \
-             ${opt1_dir%/} ${ipt_dir%/}/ 6 1 "full"  ${base_date} ${date}
-         if [ $? != 0 ];then
-                echo "$0 : full avg for $date failed"
-        fi
+    if [ "$(find ${ipt_dir%/}/*${date}_????.nc 2> /dev/null)" ];then
+         #${workdir%/}/create_time_avg ${workdir%/} \
+         #    ${opt1_dir%/} ${ipt_dir%/}/ 6 1 "full"  ${base_date} ${date}
+         #if [ $? != 0 ];then
+         #  echo "$(basename $0) : full avg for $date failed"
+        #fi
          ${workdir%/}/create_time_avg ${workdir%/} \
              ${opt2_dir%/} ${ipt_dir%/}/ 6 1 "avg" ${base_date} ${date}
          if [ $? != 0 ];then
-                echo "$0 : dom avg for $date failed"
+           echo "$(basename $0) : dom avg for $date failed"
         fi
 
     fi
-    
     done
-
-
