ksh -> bash

diff --git a/2D_create/create_2d_input_files b/2D_create/create_2d_input_files
--- a/2D_create/create_2d_input_files
+++ b/2D_create/create_2d_input_files
@@ -1,4 +1,4 @@
-#!/usr/bin/env ksh
+#!/bin/bash
 #
 ###################################################################################
 #
@@ -29,28 +29,29 @@
 ##################################################################################
 #
 # Options
+date=$(which gdate 2> /dev/null)
+if [ -z "$date" ];then
+    date=$(which date)
+fi
+if [ -z "$date" ];then
+    echo "Can't find date or gdate, if you are on osx considere installing coreutils"
+    exit 1
+fi
 
 # Set where relevant files are located
 ipt_dir=${1%/}/
 opt_dir=${2%/}/
-
+mkdir -p $opt_dir
 # Set the output filename
 outfile=${3%/}
 
 wrkdir=$(dirname $(readlink -f $0))
 
 # Set the times we require
-date_begin="${4} 0000"
-set -A array ${@}
-for i in ${array[*]};do
-    date_end="$i 1200"
-done
-
+date_begin=$(echo ${4}|sed s"/_/ /g")
+date_end=$(echo ${5}|sed s"/_/ /g")
 # Names of all the months in between our two dates
-set -A dates ${@:4}
-#set -A dates "20041001" "20041101" "20041201" "20050101" "20050201" "20050301" "20050401"
-
-
+declare -a dates=${@:6}
 ##################################################################################
 
 
@@ -63,14 +64,14 @@ var1="time,time_offset,base_time,sktsfc,spsfc,no10usfc,no10vsfc,no2tsfc,no2dsfc,
 var2="ewsssfc,nssssfc,sshfsfc,slhfsfc,ssrsfc,strsfc,tsrsfc,ttrsfc,tccsfc,ssrdsfc,strdsfc"
 
 i=0
-for date in ${dates[*]}
+for mon in ${dates[*]}
 do
 
  # Find the files required
-   file_surf[$i]=$(find ${ipt_dir}*surf*${date}*)
-   file_supp[$i]=$(find ${ipt_dir}*supp*${date}*)
+   file_surf[$i]=$(find ${ipt_dir}*surf*${mon}*)
+   file_supp[$i]=$(find ${ipt_dir}*supp*${mon}*)
 
-   file_tmp[$i]="${date}_tmp.cdf"
+   file_tmp[$i]="${mon}_tmp.cdf"
   
  # get the variables we need from the surf and supp files
    ncks -h -O -v "${var1}" "${file_surf[i]}" "${file_tmp[i]}"
@@ -81,19 +82,18 @@ done
 
 # Set baseline dates and time cutoffs ########################################
 
-base_date=${dates[0]}
-base_time=$(date -u -d "${base_date}" +%s )
+base_date=$(echo ${dates[*]}|awk '{print $1}')
+base_time=$($date -u -d "${base_date}" +%s )
 
+time_begin=$(($($date -u -d "${date_begin}" +%s ) - $($date -u -d "${base_date} 0000" +%s )))
+time_end=$(($($date -u -d "${date_end}" +%s ) - $($date -u -d "${base_date} 0000" +%s )))
 
-time_begin=$(($(date -u -d "${date_begin}" +%s ) - $(date -u -d "${base_date}" +%s )))
-time_begin=$((time_begin/86400.0))
-time_end=$(($(date -u -d "${date_end}" +%s ) - $(date -u -d "${base_date}" +%s )))
-time_end=$((time_end/86400.0))
+time_begin=$(echo $time_begin|awk '{printf("%.2f",$1/86400.0)}')
+time_end=$(echo $time_end|awk '{printf("%.2f",$1/86400.0)}')
 
-base_date=$(date -u -d @$(($base_time)) +%Y-%m-%d )
+delta=$(echo $time_end $time_begin |awk {'printf("%.2f",$1-$2)'})
 
-typeset -F2 time_begin=$time_begin
-typeset -F2 time_end=$time_end
+base_date=$($date -u -d $(($base_date)) +%Y-%m-%d )
 
 # Print some stuff to screen ###############################################s
 echo " ************************************"
@@ -103,15 +103,14 @@ echo " "
 echo " ************************************"
 echo " "
 echo "Time-series defined:"
-echo "from time = $time_begin to $time_end days after $base_date"
+echo "from $(date -u -d "$date_begin" +"%d. %b %Y %H:%M") to $(date -u -d "$date_end" +"%d. %b %Y %H:%M") (${delta} days) after $base_date"
 echo " "
-
 # concatenate files (nco knows about arm conventions in time_offset and base_time, but not in time itself
 ncrcat -h -O "${file_tmp[@]}" ${outfile}
 
 # fix the 'time' variable
-ncap -h -O -s "time = time_offset/86400" ${outfile} ${outfile}
-ncatted -h -a units,time,o,c,"days since ${dates[0]:0:4}-${dates[0]:4:2}-01 00:00:00 UTC" "${outfile}"
+ncap -h -O -s "time = time_offset^1/86400.0" ${outfile} ${outfile}
+ncatted -h -a units,time,a,c,"days since ${base_date} 00:00:00 UTC" ${outfile}
 
 # make a masking file for the domain we require
 ${wrkdir%}/make_mask_ecmwf -i "${outfile}" -o ${wrkdir%}/mask.nc -d pentagon
@@ -141,7 +140,7 @@ deltat=$(ncks -v time -d time,1,1,1 $outfile)
 deltat=$(echo ${deltat}]} | sed 's/.*\(time[1]\)*\([0-9]\.[0-9]*[0-9]\).*/\2/')
 
 deltat=$deltat
-deltat_sec=$(($deltat*86400))
+deltat_sec=$(echo $deltat|awk '{printf("%.2f",$1*86400)}')
 
 echo "Temporal resolution: $deltat_sec seconds"
 
@@ -232,13 +231,12 @@ then
    # make two files of the desired time period. One 6 hours ahead of the other
 
    # some time variables
-   typeset -F2 tfl1=$((${time_begin}+${deltat}))
-   typeset -F2 tfl2=$((${time_end}+${deltat}))
-   echo $tfl1,$tfl2
+   tfl1=$(echo ${time_begin} ${deltat} |awk '{printf("%.2f",$1+$2)}')
+   tfl2=$(echo ${time_end} ${deltat}|awk '{printf("%.2f",$1+$2)}')
    ncks -h -O -d "time,$tfl1,$tfl2" ${outfile} "${outfile%.nc}_tmp.nc"
 
-   typeset -F2 tfl1=$((${time_begin}))
-   typeset -F2 tfl2=$((${time_end}))
+   tfl1=$(echo ${time_begin} | awk '{printf("%.2f",$1)}')
+   tfl2=$(echo ${time_end} | awk '{printf("%.2f",$1)}')
    ncks -h -O -d "time,$tfl1,$tfl2" ${outfile} ${outfile}
 
    # line the two time regions up
